export const backgroundImages = {
    darkblueBackground : require('../src/img/darkbluebackground.jpg'),
}

export const mainNavTab = {
    carrousel : require('../src/img/icons/champion.png'),
    combinaisons : require('../src/img/icons/objets.png'),
    synergies : require('../src/img/icons/synergy.png'),
    tierlist : require('../src/img/icons/tierlist.png'),
}

export const championImages = {
    icons : {
        aatrox : require('../src/img/champions/AatroxSquare.png'),
        ahri : require('../src/img/champions/AhriSquare.png'),
        akali : require('../src/img/champions/AkaliSquare.png'),
        anivia : require('../src/img/champions/AniviaSquare.png'),
        ashe : require('../src/img/champions/AsheSquare.png'),
        aurelion_sol : require('../src/img/champions/Aurelion_SolSquare.png'),
        blitzcrank : require('../src/img/champions/BlitzcrankSquare.png'),
        brand : require('../src/img/champions/BrandSquare.png'),
        braum : require('../src/img/champions/BraumSquare.png'),
        chogath : require('../src/img/champions/ChoGathSquare.png'),
        darius : require('../src/img/champions/DariusSquare.png'),
        draven : require('../src/img/champions/DravenSquare.png'),
        elise : require('../src/img/champions/EliseSquare.png'),
        evelynn : require('../src/img/champions/EvelynnSquare.png'),
        fiora : require('../src/img/champions/FioraSquare.png'),
        gangplank : require('../src/img/champions/GangplankSquare.png'),
        garen : require('../src/img/champions/GarenSquare.png'),
        gnar : require('../src/img/champions/GnarSquare.png'),
        graves : require('../src/img/champions/GravesSquare.png'),
        karthus : require('../src/img/champions/KarthusSquare.png'),
        kassadin : require('../src/img/champions/KassadinSquare.png'),
        katarina : require('../src/img/champions/KatarinaSquare.png'),
        kayle : require('../src/img/champions/KayleSquare.png'),
        kennen : require('../src/img/champions/KennenSquare.png'),
        khazix : require('../src/img/champions/KhazixSquare.png'),
        kindred : require('../src/img/champions/KindredSquare.png'),
        leona : require('../src/img/champions/LeonaSquare.png'),
        lissandra : require('../src/img/champions/LissandraSquare.png'),
        lucian : require('../src/img/champions/LucianSquare.png'),
        lulu : require('../src/img/champions/LuluSquare.png'),
        miss_fortune : require('../src/img/champions/Miss_FortuneSquare.png'),
        mordekaiser : require('../src/img/champions/MordekaiserSquare.png'),
        morgana : require('../src/img/champions/MorganaSquare.png'),
        nidalee : require('../src/img/champions/NidaleeSquare.png'),
        poppy : require('../src/img/champions/PoppySquare.png'),
        pyke : require('../src/img/champions/PykeSquare.png'),
        reksai : require('../src/img/champions/RekSaiSquare.png'),
        rengar : require('../src/img/champions/RengarSquare.png'),
        sejuani : require('../src/img/champions/SejuaniSquare.png'),
        shen : require('../src/img/champions/ShenSquare.png'),
        shyvana : require('../src/img/champions/ShyvanaSquare.png'),
        swain : require('../src/img/champions/SwainSquare.png'),
        tristana : require('../src/img/champions/TristanaSquare.png'),
        twisted_fate : require('../src/img/champions/Twisted_FateSquare.png'),
        varus : require('../src/img/champions/VarusSquare.png'),
        vayne : require('../src/img/champions/VayneSquare.png'),
        veigar : require('../src/img/champions/VeigarSquare.png'),
        volibear : require('../src/img/champions/VolibearSquare.png'),
        warwick : require('../src/img/champions/WarwickSquare.png'),
        yasuo : require('../src/img/champions/YasuoSquare.png'),
        zed : require('../src/img/champions/ZedSquare.png'),
    },
    render : {
        aatrox : require('../src/img/champions/Aatrox_Render.png'),
        ahri : require('../src/img/champions/Ahri_Render.png'),
        akali : require('../src/img/champions/Akali_Render.png'),
        anivia : require('../src/img/champions/Anivia_Render.png'),
        ashe : require('../src/img/champions/Ashe_Render.png'),
        aurelion_sol : require('../src/img/champions/Aurelion_Sol_Render.png'),
        blitzcrank : require('../src/img/champions/Blitzcrank_Render.png'),
        brand : require('../src/img/champions/Brand_Render.png'),
        braum : require('../src/img/champions/Braum_Render.png'),
        chogath : require('../src/img/champions/ChoGath_Render.png'),
        darius : require('../src/img/champions/Darius_Render.png'),
        draven : require('../src/img/champions/Draven_Render.png'),
        elise : require('../src/img/champions/Elise_Render.png'),
        evelynn : require('../src/img/champions/Evelynn_Render.png'),
        fiora : require('../src/img/champions/Fiora_Render.png'),
        gangplank : require('../src/img/champions/Gangplank_Render.png'),
        garen : require('../src/img/champions/Garen_Render.png'),
        gnar : require('../src/img/champions/Gnar_Render.png'),
        graves : require('../src/img/champions/Graves_Render.png'),
        karthus : require('../src/img/champions/Karthus_Render.png'),
        kassadin : require('../src/img/champions/Kassadin_Render.png'),
        katarina : require('../src/img/champions/Katarina_Render.png'),
        kayle : require('../src/img/champions/Kayle_Render.png'),
        kennen : require('../src/img/champions/Kennen_Render.png'),
        khazix : require('../src/img/champions/Khazix_Render.png'),
        kindred : require('../src/img/champions/Kindred_Render.png'),
        leona : require('../src/img/champions/Leona_Render.png'),
        lissandra : require('../src/img/champions/Lissandra_Render.png'),
        lucian : require('../src/img/champions/Lucian_Render.png'),
        lulu : require('../src/img/champions/Lulu_Render.png'),
        miss_fortune : require('../src/img/champions/Miss_Fortune_Render.png'),
        mordekaiser : require('../src/img/champions/Mordekaiser_Render.png'),
        morgana : require('../src/img/champions/Morgana_Render.png'),
        nidalee : require('../src/img/champions/Nidalee_Render.png'),
        poppy : require('../src/img/champions/Poppy_Render.png'),
        pyke : require('../src/img/champions/Pyke_Render.png'),
        reksai : require('../src/img/champions/RekSai_Render.png'),
        rengar : require('../src/img/champions/Rengar_Render.png'),
        sejuani : require('../src/img/champions/Sejuani_Render.png'),
        shen : require('../src/img/champions/Shen_Render.png'),
        shyvana : require('../src/img/champions/Shyvana_Render.png'),
        swain : require('../src/img/champions/Swain_Render.png'),
        tristana : require('../src/img/champions/Tristana_Render.png'),
        twisted_fate : require('../src/img/champions/Twisted_Fate_Render.png'),
        varus : require('../src/img/champions/Varus_Render.png'),
        vayne : require('../src/img/champions/Vayne_Render.png'),
        veigar : require('../src/img/champions/Veigar_Render.png'),
        volibear : require('../src/img/champions/Volibear_Render.png'),
        warwick : require('../src/img/champions/Warwick_Render.png'),
        yasuo : require('../src/img/champions/Yasuo_Render.png'),
        zed : require('../src/img/champions/Zed_Render.png'),
    }
}
export const originIcons = {
    demon : require('../src/img/origine/Demon_TFT_icon.png'),
    dragon : require('../src/img/origine/Dragon_TFT_icon.png'),
    exile : require('../src/img/origine/Exile_TFT_icon.png'),
    glacial : require('../src/img/origine/Glacial_TFT_icon.png'),
    imperial : require('../src/img/origine/Imperial_TFT_icon.png'),
    ninja : require('../src/img/origine/Ninja_TFT_icon.png'),
    noble : require('../src/img/origine/Noble_TFT_icon.png'),
    phantome : require('../src/img/origine/Phantom_TFT_icon.png'),
    pirate : require('../src/img/origine/Pirate_TFT_icon.png'),
    robot : require('../src/img/origine/Robot_TFT_icon.png'),
    void : require('../src/img/origine/Void_TFT_icon.png'),
    sauvage : require('../src/img/origine/Wild_TFT_icon.png'),
    yordle : require('../src/img/origine/Yordle_TFT_icon.png'),
}
export const classIcons = {
    assassin : require('../src/img/classe/Assassin_TFT_icon.png'),
    blademaster : require('../src/img/classe/Blademaster_TFT_icon.png'),
    bagarreur : require('../src/img/classe/Brawler_TFT_icon.png'),
    elementaliste : require('../src/img/classe/Elementalist_TFT_icon.png'),
    guardien : require('../src/img/classe/Guardian_TFT_icon.png'),
    pistolero : require('../src/img/classe/Gunslinger_TFT_icon.png'),
    chevalier : require('../src/img/classe/Knight_TFT_icon.png'),
    ranger : require('../src/img/classe/Ranger_TFT_icon.png'),
    shapeshifter : require('../src/img/classe/Shapeshifter_TFT_icon.png'),
    sorcier : require('../src/img/classe/Sorcerer_TFT_icon.png'),
}
export const complexObjects = {
    botrk : require('../src/img/objets/botrk.png'),
    darkin : require('../src/img/objets/Darkin.png'),
    dervish : require('../src/img/objets/Dervish_Blade_item.png'),
    griffe : require('../src/img/objets/Dragon_Claw_item.png'),
    force_nature : require('../src/img/objets/Force_of_Nature_item.png'),
    coeur_gele : require('../src/img/objets/Frozen_Heart_item.png'),
    maillet_gele : require('../src/img/objets/Frozen_Mallet_item.png'),
    ange_guardien : require('../src/img/objets/Guardian_Angel_item.png'),
    guinsoo : require('../src/img/objets/Guinsoo_item.png'),
    pistolame : require('../src/img/objets/Hextech_Gunblade_item.png'),
    silence : require('../src/img/objets/Hush_item.png'),
    lame_infinie : require('../src/img/objets/Infinity_Edge_item.png'),
    ionic : require('../src/img/objets/Ionic_Spark_item.png'),
    solari : require('../src/img/objets//Iron_Solari_item.png'),
    voeu_chevalier : require('../src/img/objets/Knight_Vow_item.png'),
    luden : require('../src/img/objets/Luden_item.png'),
    morellonomicon : require('../src/img/objets/Morellonomicon_item.png'),
    phantom_dancer : require('../src/img/objets/Phantom_Dancer_item.png'),
    canon_ultrarapide : require('../src/img/objets/Rapid_Firecannon_item.png'),
    buff_rouge : require('../src/img/objets/Red_BuffSquare.png'),
    redemption : require('../src/img/objets/Redemption_item.png'),
    runaan : require('../src/img/objets/Runaan_item.png'),
    seraph : require('../src/img/objets/Seraph_item.png'),
    shojin : require('../src/img/objets/Spear_of_Shojin_item.png'),
    statick : require('../src/img/objets/Statikk_Shiv_item.png'),
    rabadon : require('../src/img/objets/Rabadon_item.png'),
    briseur : require('../src/img/objets/Sword_Breaker_item.png'),
    epee_divin : require('../src/img/objets/Sword_of_the_Divine_item.png'),
    bt : require('../src/img/objets/The_Bloodthirster_item.png'),
    thornmail : require('../src/img/objets/Thornmail_item.png'),
    hydre_titanic : require('../src/img/objets/Titanic_Hydra_item.png'),
    warmog : require('../src/img/objets/Warmog_item.png'),
    youmuu : require('../src/img/objets/Youmuu_item.png'),
    yuumi : require('../src/img/objets/Yuumi.png'),
    zeke : require('../src/img/objets/Zeke_item.png'),
    zephyr : require('../src/img/objets/Zephyr_item.png'),
}

export const tabBarIconsObjets = {
    arc : require('../src/img/objets/Recurve_Bow_item.png'),
    baguette : require('../src/img/objets/Needlessly_Large_Rod_item.png'),
    bf : require('../src/img/objets/BF.png'),
    ceinture : require('../src/img/objets/Giant_Belt_item.png'),
    cote_de_maille : require('../src/img/objets/Chain_Vest_item.png'),
    larme : require('../src/img/objets/Tear.png'),
    negatron : require('../src/img/objets/Negatron_Cloak_item.png'),
    spatule : require('../src/img/objets/Spatula_item.png'),
}