import React, {Component} from 'react';
import {StyleSheet, View, ScrollView, Button, Image, Modal, TouchableHighlight,} from 'react-native';
import {originIcons, classIcons, championImages, complexObjects} from '../constants/images';
import { Tooltip, Text } from 'react-native-elements';
import DetailChamp from './DetailChamp';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    flexDirection : 'row',
    flexWrap : 'wrap',
    justifyContent: 'center',
    alignItems : 'center',
  },
  itemContainer : {
    width: 50,
    margin : 10,
    alignItems : 'center',
    justifyContent : 'center',
  }
});

export default class Champions extends Component {
  state = {
    champArray : {
      aatrox: {
        name: "Aatrox",
        img: championImages.icons.aatrox,
        img_render: championImages.render.aatrox,
        propIconsArray : [originIcons.demon,classIcons.blademaster],
        propArray : ["Démon","Blademaster"],
        dmgArray : [65,117,234],
        hpArray : [700,1350,2700],
        as : 0.65,
        mr : 20,
        armure : 25,
        portee : 1,
        cout : 3,
        titreUlt: "La lame du Darkin",
        descriptionUlt : "Aatrox fend l'espace devant lui infligeant 250/600/950 dégats",
        recommandedItemsArray : [complexObjects.pistolame, complexObjects.griffe, complexObjects.phantom_dancer]
      },
      ahri: {
        name: "Ahri",
        img: championImages.icons.ahri,
        img_render: championImages.render.ahri,
        propIconsArray : [originIcons.sauvage,classIcons.sorcier],
        propArray : ["Sauvage","Sorcier"],
        dmgArray : [50,90,180],
        hpArray : [450,810,1620],
        as : 0.55,
        mr : 20,
        armure : 20,
        portee : 3,
        cout : 2,
        titreUlt: "Orbe spirituelle",
        descriptionUlt : "Ahri lance son orbe en ligne droite infligeant 100/200/300 dégats par ennemi traversé",
        recommandedItemsArray : [complexObjects.shojin, complexObjects.guinsoo, complexObjects.rabadon]
      },
      akali: {
        name: "Akali",
        img: championImages.icons.akali,
        img_render: championImages.render.akali,
        propIconsArray : [originIcons.ninja,classIcons.assassin],
        propArray : ["Ninja","Assassin"],
        dmgArray : [70,126,252],
        hpArray : [650,1170,2340],
        as : 0.7,
        mr : 20,
        armure : 20,
        portee : 1,
        cout : 4,
        titreUlt: "Frappe des cinq points",
        descriptionUlt : "Inflige 150/275/400 dégats magique dans un cone. Peut être un coup critique",
        recommandedItemsArray : [complexObjects.seraph, complexObjects.phantom_dancer, complexObjects.rabadon]

      },
      anivia: {
        name: "Anivia",
        img: championImages.icons.anivia,
        img_render: championImages.render.anivia,
        propIconsArray : [originIcons.glacial,classIcons.elementaliste],
        propArray : ["Glacial","Elémentaliste"],
        dmgArray : [40,72,144],
        hpArray : [650,1170,2340],
        as : 0.6,
        mr : 20,
        armure : 20,
        portee : 3,
        cout : 5,
        titreUlt: "Tempête glaciale",
        descriptionUlt : "Anivia invoque une zone de froid, infligeant 700/950/1200 dégats magiques et ralentissant la vitesse d'attaque de 50/70/90% pendant 8scd",
        recommandedItemsArray : [complexObjects.seraph, complexObjects.morellonomicon, complexObjects.seraph]
      },
      ashe: {
        name: "Ashe",
        img: championImages.icons.ashe,
        img_render: championImages.render.ashe,
        propIconsArray : [originIcons.glacial,classIcons.ranger],
        propArray : ["Glacial","Ranger"],
        dmgArray : [65,120,226],
        hpArray : [550,990,1980],
        as : 0.7,
        mr : 20,
        armure : 20,
        portee : 4,
        cout : 3,
        titreUlt: "Flèche de cristal enchantée",
        descriptionUlt : "Ashe décoche une flèche de cristal infligeant 200/400/600 et étourdissant pour 1/1.5/2 scd un ennemi aléatoire",
        recommandedItemsArray : [complexObjects.shojin, complexObjects.canon_ultrarapide, complexObjects.phantom_dancer]

      },
      aurelion_sol: {
        name: "Aurelion Sol",
        img: championImages.icons.aurelion_sol,
        img_render: championImages.render.aurelion_sol,
        propIconsArray : [originIcons.dragon,classIcons.sorcier],
        propArray : ["Dragon","Sorcer"],
        dmgArray : [40,72,144],
        hpArray : [650,1080,2160],
        as : 0.6,
        mr : 20,
        armure : 20,
        portee : 3,
        cout : 4,
        titreUlt: "Voix de lumière",
        descriptionUlt : "Aurelion expire une bourrasque de feu en ligne droite, infligeant 250/500/750 de dégats aux ennemis touchés",
        recommandedItemsArray : [complexObjects.shojin, complexObjects.guinsoo, complexObjects.rabadon]

      },
      blitzcrank: {
        name: "Blitzcrank",
        img: championImages.icons.blitzcrank,
        img_render: championImages.render.blitzcrank,
        propIconsArray : [originIcons.robot,classIcons.bagarreur],
        propArray : ["Robot","Bagarreur"],
        dmgArray : [50,90,180],
        hpArray : [600,1080,2160],
        as : 0.5,
        mr : 20,
        armure : 35,
        portee : 1,
        cout : 2,
        titreUlt: "Attrape Rocket",
        descriptionUlt : "Blitzcrank attire l'ennemi le plus éloigné et lui inflige 100/450/800 dégat, l'étourdissant 2.5 secondes",
        recommandedItemsArray : [complexObjects.guinsoo, complexObjects.shojin, complexObjects.rabadon]

      },
      brand: {
        name: "Brand",
        img: championImages.icons.brand,
        img_render: championImages.render.brand,
        propIconsArray : [originIcons.demon,classIcons.elementaliste],
        propArray : ["Demon","Elémentaliste"],
        dmgArray : [60,108,216],
        hpArray : [700,1260,2520],
        as : 0.6,
        mr : 20,
        armure : 25,
        portee : 3,
        cout : 4,
        titreUlt: "Pyroclasme",
        descriptionUlt : "Brand expédie une boule de feu rebondissant 4/4/6 fois et infligeant 200/375/550 dégats",
        recommandedItemsArray : [complexObjects.shojin, complexObjects.guinsoo, complexObjects.rabadon]

      },
      braum: {
        name: "Braum",
        img: championImages.icons.braum,
        img_render: championImages.render.braum,
        propIconsArray : [originIcons.glacial,classIcons.guardien],
        propArray : ["Glacial","Guardien"],
        dmgArray : [40,72,144],
        hpArray : [750,1350,2700],
        as : 0.6,
        mr : 20,
        armure : 75,
        portee : 1,
        cout : 2,
        titreUlt: "Incassable",
        descriptionUlt : "Braum invoque un bouclier bloquant de 70/80/90% tout les dégats entrant pendant 4 secondes",
        recommandedItemsArray : [complexObjects.thornmail, complexObjects.solari, complexObjects.zeke]

      },
      chogath: {
        name: "Cho'gath",
        img: championImages.icons.chogath,
        img_render: championImages.render.chogath,
        propIconsArray : [originIcons.void,classIcons.bagarreur],
        propArray : ["du Vide","Bagarreur"],
        dmgArray : [70,126,252],
        hpArray : [1000,1800,3600],
        as : 0.6,
        mr : 20,
        armure : 20,
        portee : 1,
        cout : 4,
        titreUlt: "Tremblement",
        descriptionUlt : "Cho'Gath fait trembler une grande zone, étoudissant pendant 1.5/1.75/2 secondes les ennemis et infligeant 250/500/750 dégats magiques",
        recommandedItemsArray : [complexObjects.pistolame, complexObjects.griffe, complexObjects.phantom_dancer]

      },
      darius: {
        name: "Darius",
        img: championImages.icons.darius,
        img_render: championImages.render.darius,
        propIconsArray : [originIcons.imperial,classIcons.chevalier],
        propArray : ["Imperial","Chevalier"],
        dmgArray : [50,90,180],
        hpArray : [600,1080,2160],
        as : 0.5,
        mr : 20,
        armure : 40,
        portee : 1,
        cout : 1,
        titreUlt: "Décimer",
        descriptionUlt : "Darius fait tournoyer sa hache, le soignant de 50/100/150pv et infligeant 75/150/225 dégats par ennemi touché ",
        recommandedItemsArray : [complexObjects.pistolame, complexObjects.griffe, complexObjects.phantom_dancer]

      },
      draven: {
        name: "Draven",
        img: championImages.icons.draven,
        img_render: championImages.render.draven,
        propIconsArray : [originIcons.imperial,classIcons.blademaster],
        propArray : ["Imperial","Blademaster"],
        dmgArray : [75,135,270],
        hpArray : [700,1260,2520],
        as : 0.75,
        mr : 20,
        armure : 25,
        portee : 3,
        cout : 4,
        titreUlt: "Haches tournoyantes",
        descriptionUlt : "Draven gagne 50/100/150% de dégats et 30/45/60% de vitesse d'attaque pendant 8 secondes",
        recommandedItemsArray : [complexObjects.bt, complexObjects.dervish, complexObjects.canon_ultrarapide]

      },
      elise: {
        name: "Elise",
        img: championImages.icons.elise,
        img_render: championImages.render.elise,
        propIconsArray : [originIcons.demon,classIcons.shapeshifter],
        propArray : ["Demon","Changeforme"],
        dmgArray : [40,72,144],
        hpArray : [450,810,1620],
        as : 0.6,
        mr : 20,
        armure : 20,
        portee : 2,
        cout : 1,
        titreUlt: "Forme araignée",
        descriptionUlt : "Elise tire un cocon étourdissant un ennemi, invoque 1/2/4 araignées (500px) et se transforme en araignée géante, gagnant 60/90/120% de vol de vie",
        recommandedItemsArray : [complexObjects.buff_rouge, complexObjects.griffe, complexObjects.phantom_dancer]

      },
      evelynn: {
        name: "Evelynn",
        img: championImages.icons.evelynn,
        img_render: championImages.render.evelynn,
        propIconsArray : [originIcons.demon,classIcons.assassin],
        propArray : ["Demon","Assassin"],
        dmgArray : [70,108,216],
        hpArray : [550,990,1980],
        as : 0.6,
        mr : 20,
        armure : 20,
        portee : 1,
        cout : 3,
        titreUlt: "Dernière caresse",
        descriptionUlt : "Evelynn inflige 200/300/400 dégats aux trois ennemis les plus proches, les executants (3x/5x/7x les dégats) si ils ont moins de 65% de leurs points de vie",
        recommandedItemsArray : [complexObjects.shojin, complexObjects.guinsoo, complexObjects.rabadon]

      },
      fiora: {
        name: "Fiora",
        img: championImages.icons.fiora,
        img_render: championImages.render.fiora,
        propIconsArray : [originIcons.noble,classIcons.chevalier],
        propArray : ["Noble","Chevalier"],
        dmgArray : [40,72,144],
        hpArray : [400,720,1440],
        as : 1,
        mr : 20,
        armure : 25,
        portee : 1,
        cout : 1,
        titreUlt: "Riposte",
        descriptionUlt : "Fiora est immunisée contre tout les dégats, après 1.5 secondes, elle inflige 25/100/175 dégats et étourdi 1.5 secondes l'ennemi le proche proche",
        recommandedItemsArray : [complexObjects.pistolame, complexObjects.griffe, complexObjects.phantom_dancer]

      },
      gangplank: {
        name: "Gangplank",
        img: championImages.icons.gangplank,
        img_render: championImages.render.gangplank,
        propIconsArray : [originIcons.demon,classIcons.blademaster, classIcons.pistolero],
        propArray : ["Pirate","Blademaster","Pistolero"],
        dmgArray : [55,99,198],
        hpArray : [700,1260,2520],
        as : 0.65,
        mr : 20,
        armure : 20,
        portee : 1,
        cout : 3,
        titreUlt: "Barils de poudre",
        descriptionUlt : "Gangplank pose des barils, à l'activation, chaque baril inflige 200/325/450 dégats",
        recommandedItemsArray : [complexObjects.pistolame, complexObjects.griffe, complexObjects.phantom_dancer]

      },
      garen: {
        name: "Garen",
        img: championImages.icons.garen,
        img_render: championImages.render.garen,
        propIconsArray : [originIcons.noble,classIcons.chevalier],
        propArray : ["Noble","Chevalier"],
        dmgArray : [50,90,185],
        hpArray : [600,1080,2160],
        as : 0.6,
        mr : 20,
        armure : 40,
        portee : 1,
        cout : 1,
        titreUlt: "Jugement",
        descriptionUlt : "Spin to win ! Garen tournoi infligeant 360/585/810 dégats (50/65/80 par tick) et devient insensible aux dégats magiques",
        recommandedItemsArray : [complexObjects.morellonomicon, complexObjects.coeur_gele, complexObjects.phantom_dancer]

      },
      gnar: {
        name: "Gnar",
        img: championImages.icons.gnar,
        img_render: championImages.render.gnar,
        propIconsArray : [originIcons.sauvage, classIcons.bagarreur ,classIcons.elementaliste],
        propArray : ["Sauvage","Bagarreur","Elémentaliste"],
        dmgArray : [50,91,182],
        hpArray : [750,1350,2700],
        as : 0.7,
        mr : 20,
        armure : 30,
        portee : 2,
        cout : 4,
        titreUlt: "GNAR!",
        descriptionUlt : "Gnar se transforme, bondissant et repoussant les ennemis, infligeant 200/300/400 dégats et étourdissant pendant 2 secondes. Il gagne 300/600/900pv et 30/60/90 dégat/coup",
        recommandedItemsArray : [complexObjects.warmog, complexObjects.griffe, complexObjects.phantom_dancer]

      },
      graves: {
        name: "Graves",
        img: championImages.icons.graves,
        img_render: championImages.render.graves,
        propIconsArray : [originIcons.pirate,classIcons.pistolero],
        propArray : ["Pirate","Pistolero"],
        dmgArray : [55,99,1620],
        hpArray : [450,810,1620],
        as : 0.55,
        mr : 20,
        armure : 20,
        portee : 1,
        cout : 1,
        titreUlt: "Buckshot",
        descriptionUlt : "Compétence passive, les attaques de Graves touche aussi les ennemis proches (+0/10/20% de dégats)",
        recommandedItemsArray : [complexObjects.buff_rouge, complexObjects.briseur, complexObjects.dervish]

      },
      karthus: {
        name: "Karthus",
        img: championImages.icons.karthus,
        img_render: championImages.render.karthus,
        propIconsArray : [originIcons.phantome,classIcons.sorcier],
        propArray : ["Phantôme","Sorcier"],
        dmgArray : [65,117,234],
        hpArray : [850,1530,3060],
        as : 0.65,
        mr : 20,
        armure : 25,
        portee : 3,
        cout : 5,
        titreUlt: "Requiem",
        descriptionUlt : "Karthus canalise son ultimate afin d'infliger 400/700/1000 dégats à 5/9/13 ennemis",
        recommandedItemsArray : [complexObjects.seraph, complexObjects.seraph, complexObjects.rabadon]

      },
      kassadin: {
        name: "Kassadin",
        img: championImages.icons.kassadin,
        img_render: championImages.render.kassadin,
        propIconsArray : [originIcons.void,classIcons.sorcier],
        propArray : ["du Vide","Sorcier"],
        dmgArray : [55,100,230],
        hpArray : [550,990,1980],
        as : 0.6,
        mr : 20,
        armure : 25,
        portee : 1,
        cout : 1,
        titreUlt: "Lame du néant",
        descriptionUlt : "Les attaques de Kassadin vole 0/20/40 mana de l'ennemi, le convertissant en un bouclier de 4 secondes",
        recommandedItemsArray : [complexObjects.pistolame, complexObjects.griffe, complexObjects.phantom_dancer]

      },
      katarina: {
        name: "Katarina",
        img: championImages.icons.katarina,
        img_render: championImages.render.katarina,
        propIconsArray : [originIcons.imperial,classIcons.assassin],
        propArray : ["Imperial","Assassin"],
        dmgArray : [50,90,180],
        hpArray : [450,810,1620],
        as : 0.6,
        mr : 20,
        armure : 20,
        portee : 1,
        cout : 4,
        titreUlt: "Lotus mortel",
        descriptionUlt : 'Katarina tournoie pendant 2.5 secondes infligeant 40/60/80 dégats par tick et applique \"soins réduits\". 6 ticks par seconde sur 4/6/8 cibles',
        recommandedItemsArray : [complexObjects.seraph, complexObjects.morellonomicon, complexObjects.pistolame]

      },
      kayle: {
        name: "Kayle",
        img: championImages.icons.kayle,
        img_render: championImages.render.kayle,
        propIconsArray : [originIcons.noble,classIcons.chevalier],
        propArray : ["Noble","Chevalier"],
        dmgArray : [60,108,216],
        hpArray : [750,1307,2400],
        as : 1.1,
        mr : 20,
        armure : 40,
        portee : 3,
        cout : 5,
        titreUlt: "Jugement Divin",
        descriptionUlt : "Kayle envoie un bouclier de 500/800/1100pv à 1/2/3 alliés pendant 2/3/4 secondes ",
        recommandedItemsArray : [complexObjects.shojin, complexObjects.guinsoo, complexObjects.seraph]

      },
      kennen: {
        name: "Kennen",
        img: championImages.icons.kennen,
        img_render: championImages.render.kennen,
        propIconsArray : [originIcons.ninja,originIcons.yordle, classIcons.elementaliste],
        propArray : ["Ninja","Yordle", "Elémentaliste"],
        dmgArray : [70,126,252],
        hpArray : [550,990,1980],
        as : 0.65,
        mr : 20,
        armure : 20,
        portee : 2,
        cout : 3,
        titreUlt: "Maelstrom tranchant",
        descriptionUlt : "Kennen invoque une tempête autour de lui, étourdissant 1.5s et infligeant 225/450/675 totaux (50/80/110 par tick)",
        recommandedItemsArray : [complexObjects.morellonomicon, complexObjects.griffe, complexObjects.phantom_dancer]

      },
      khazix: {
        name: "Kha'zix",
        img: championImages.icons.khazix,
        img_render: championImages.render.khazix,
        propIconsArray : [originIcons.void,classIcons.assassin],
        propArray : ["du Vide","Assassin"],
        dmgArray : [55,99,220],
        hpArray : [500,900,1800],
        as : 0.6,
        mr : 20,
        armure : 20,
        portee : 1,
        cout : 1,
        titreUlt: "Gouter leur peur",
        descriptionUlt : "Kha'zix frappe pour  150/300/450 dégats, infligeant 200/400/600 dégts supplémentaire en cas de cible isolée",
        recommandedItemsArray : [complexObjects.lame_infinie, complexObjects.canon_ultrarapide, complexObjects.phantom_dancer]

      },
      kindred: {
        name: "Kindred",
        img: championImages.icons.kindred,
        img_render: championImages.render.kindred,
        propIconsArray : [originIcons.phantome,classIcons.ranger],
        propArray : ["Phantôme","Ranger"],
        dmgArray : [55,99,198],
        hpArray : [600,1080,2160],
        as : 0.65,
        mr : 20,
        armure : 20,
        portee : 3,
        cout : 4,
        titreUlt: "Repos de l'agneau",
        descriptionUlt : "Kindred créé une zone pendant 4/5/6 secondes autour de lui, empéchant ses alliés de passer sous 300/600/900 pv ou de mourir",
        recommandedItemsArray : [complexObjects.zephyr, complexObjects.solari, complexObjects.zeke]

      },
      leona: {
        name: "Leona",
        img: championImages.icons.leona,
        img_render: championImages.render.leona,
        propIconsArray : [originIcons.noble,classIcons.guardien],
        propArray : ["Noble","Gardien"],
        dmgArray : [45,81,162],
        hpArray : [750,1350,2700],
        as : 0.55,
        mr : 20,
        armure : 100,
        portee : 1,
        cout : 4,
        titreUlt: "Déflagration solaire",
        descriptionUlt : "Leona invoque un rayon solaire, étourdissant tout les ennemis au centre (5/8/11 secondes) et infligeant des dégats (175/250/325)",
        recommandedItemsArray : [complexObjects.coeur_gele, complexObjects.zeke, complexObjects.solari]

      },
      lissandra: {
        name: "Lissandra",
        img: championImages.icons.lissandra,
        img_render: championImages.render.lissandra,
        propIconsArray : [originIcons.glacial,classIcons.elementaliste],
        propArray : ["Glacial","Elémentaliste"],
        dmgArray : [40,72,144],
        hpArray : [450,810,1620],
        as : 0.6,
        mr : 20,
        armure : 20,
        portee : 2,
        cout : 2,
        titreUlt: "Tombe gelée",
        descriptionUlt : "Lissandra enferme sa cible (1.5scd) dans la glace, infligeant des dégats (150/275/400) aux ennemis a proximité et les ralentissants (0/3/3scd). Sous 50% de ses PV, elle se cible elle-même (2scd)",
        recommandedItemsArray : [complexObjects.zephyr, complexObjects.solari, complexObjects.zeke]

      },
      lucian: {
        name: "Lucian",
        img: championImages.icons.lucian,
        img_render: championImages.render.lucian,
        propIconsArray : [originIcons.noble,classIcons.pistolero],
        propArray : ["Noble","Pistolero"],
        dmgArray : [65,117,234],
        hpArray : [600,1080,2160],
        as : 0.65,
        mr : 20,
        armure : 25,
        portee : 3,
        cout : 2,
        titreUlt: "Poursuite infatiguable",
        descriptionUlt : "Lucian bondit en sécurité et attaque un ennemi deux fois, une fois avec ses dégats physique et une fois avec ses dégats magiques (150/250/350 dégats). 200% sur les minions",
        recommandedItemsArray : [complexObjects.seraph, complexObjects.dervish, complexObjects.buff_rouge]

      },
      lulu: {
        name: "Lulu",
        img: championImages.icons.lulu,
        img_render: championImages.render.lulu,
        propIconsArray : [originIcons.yordle,classIcons.sorcier],
        propArray : ["Yordle","Sorcier"],
        dmgArray : [50,90,180],
        hpArray : [500,900,1800],
        as : 0.6,
        mr : 20,
        armure : 20,
        portee : 2,
        cout : 2,
        titreUlt: "Croissance sauvage",
        descriptionUlt : "Lulu booste la vie de 1/2/3 alliés (300/475/650pv) et repousse les ennemis pendant 1.5 secondes",
        recommandedItemsArray : [complexObjects.guinsoo, complexObjects.shojin, complexObjects.shojin]

      },
      miss_fortune: {
        name: "Miss Fortune",
        img: championImages.icons.miss_fortune,
        img_render: championImages.render.miss_fortune,
        propIconsArray : [originIcons.pirate,classIcons.pistolero],
        propArray : ["Pirate","Pistolero"],
        dmgArray : [75,135,270],
        hpArray : [650,1170,2340],
        as : 0.85,
        mr : 20,
        armure : 20,
        portee : 3,
        cout : 5,
        titreUlt: "Bullet Time",
        descriptionUlt : "Miss Fortune tire 14 vagues en forme de cône, infligeant 800/1250/1700 dégats en 3 secondes",
        recommandedItemsArray : [complexObjects.seraph, complexObjects.shojin, complexObjects.morellonomicon]

      },
      mordekaiser: {
        name: "Mordekaiser",
        img: championImages.icons.mordekaiser,
        img_render: championImages.render.mordekaiser,
        propIconsArray : [originIcons.phantome,classIcons.chevalier],
        propArray : ["Phantôme","Chevalier"],
        dmgArray : [50,90,180],
        hpArray : [550,990,1980],
        as : 0.5,
        mr : 20,
        armure : 40,
        portee : 1,
        cout : 1,
        titreUlt: "Obliterer",
        descriptionUlt : "Mordekaisr écrase sa massue en ligne droite sur trois cases, infligeant 50/150/250 dégats",
        recommandedItemsArray : [complexObjects.coeur_gele, complexObjects.griffe, complexObjects.phantom_dancer]

      },
      morgana: {
        name: "Morgana",
        img: championImages.icons.morgana,
        img_render: championImages.render.morgana,
        propIconsArray : [originIcons.demon,classIcons.sorcier],
        propArray : ["Demon","Sorcier"],
        dmgArray : [50,90,180],
        hpArray : [650,1170,2340],
        as : 0.6,
        mr : 20,
        armure : 20,
        portee : 2,
        cout : 3,
        titreUlt: "Chaines de l'âme",
        descriptionUlt : "Morgana lance des chaines sur les ennemis proches (3 cases), infligeant 200/325/450 dégats et les étouridissant pendant 2/4/6scd après 3 secondes",
        recommandedItemsArray : [complexObjects.morellonomicon, complexObjects.griffe, complexObjects.phantom_dancer]

      },
      nidalee: {
        name: "Nidalee",
        img: championImages.icons.nidalee,
        img_render: championImages.render.nidalee,
        propIconsArray : [originIcons.sauvage,classIcons.shapeshifter],
        propArray : ["Sauvage","Changeforme"],
        dmgArray : [50,90,180],
        hpArray : [500,900,1800],
        as : 0.65,
        mr : 20,
        armure : 20,
        portee : 3,
        cout : 1,
        titreUlt: "Instinct sauvage",
        descriptionUlt : "Nidalee se soigne (150/375/600 pv/seconde pour 6 secondes) ainsi que son plus faible allié, puis se transforme (+20/70/120 dégats/coup)",
        recommandedItemsArray : [complexObjects.guinsoo, complexObjects.griffe, complexObjects.phantom_dancer]

      },
      poppy: {
        name: "Poppy",
        img: championImages.icons.poppy,
        img_render: championImages.render.poppy,
        propIconsArray : [originIcons.yordle,classIcons.chevalier],
        propArray : ["Yordle","Chevalier"],
        dmgArray : [50,90,180],
        hpArray : [800,1440,2880],
        as : 0.5,
        mr : 20,
        armure : 40,
        portee : 1,
        cout : 3,
        titreUlt: "Verdicte du gardien",
        descriptionUlt : "Poppy frappe avec son marteau (300/500/700 dégats), repoussant les ennemis (1/2/3) proches pendant une seconde et les étourdissants 2/3/4 secondes",
        recommandedItemsArray : [complexObjects.thornmail, complexObjects.griffe, complexObjects.phantom_dancer]

      },
      pyke: {
        name: "Pyke",
        img: championImages.icons.pyke,
        img_render: championImages.render.pyke,
        propIconsArray : [originIcons.pirate,classIcons.assassin],
        propArray : ["Pirate","Assassin"],
        dmgArray : [60,108,216],
        hpArray : [600,1080,2160],
        as : 0.55,
        mr : 20,
        armure : 25,
        portee : 1,
        cout : 2,
        titreUlt: "Flot du phantôme",
        descriptionUlt : "Pyke fonce derrière l'ennemi le plus lointain créant une après-image qui frappe (150/200/250 dégats) et étourdit (2/2.5/3 secondes) les ennemis qu'il traverse",
        recommandedItemsArray : [complexObjects.shojin, complexObjects.shojin, complexObjects.guinsoo]

      },
      reksai: {
        name: "Rek'Sai",
        img: championImages.icons.reksai,
        img_render: championImages.render.reksai,
        propIconsArray : [originIcons.void,classIcons.bagarreur],
        propArray : ["du Vide","Bagarreur"],
        dmgArray : [50,85,180],
        hpArray : [650,1170,2340],
        as : 0.65,
        mr : 20,
        armure : 20,
        portee : 1,
        cout : 2,
        titreUlt: "Enfouir",
        descriptionUlt : "Rek'Sai s'enfoui pendant une seconde, devenant inciblable et se soignant (150/300/450), puis remonte infligeant 200/350/500 dégats et repoussant l'ennemi 1.75 seconde",
        recommandedItemsArray : [complexObjects.coeur_gele, complexObjects.griffe, complexObjects.hydre_titanic]

      },
      rengar: {
        name: "Rengar",
        img: championImages.icons.rengar,
        img_render: championImages.render.rengar,
        propIconsArray : [originIcons.sauvage,classIcons.assassin],
        propArray : ["Sauvage","Assassin"],
        dmgArray : [70,108,216],
        hpArray : [550,990,1980],
        as : 0.60,
        mr : 20,
        armure : 20,
        portee : 1,
        cout : 3,
        titreUlt: "Sauvagerie",
        descriptionUlt : "Rengar bondit sur l'ennemi le plus faible et le poignarde (dégats * 2.1/3.2/4.3), il gagne un buff de 40/70/100% de vitesse d'attaque et 25% de chance de critique pendant 6 secondes",
        recommandedItemsArray : [complexObjects.lame_infinie, complexObjects.canon_ultrarapide, complexObjects.phantom_dancer]

      },
      sejuani: {
        name: "Sejuani",
        img: championImages.icons.sejuani,
        img_render: championImages.render.sejuani,
        propIconsArray : [originIcons.glacial,classIcons.chevalier],
        propArray : ["Glacial","Chevalier"],
        dmgArray : [45,81,162],
        hpArray : [850,1530,3060],
        as : 0.55,
        mr : 25,
        armure : 40,
        portee : 1,
        cout : 4,
        titreUlt: "Prison de glace",
        descriptionUlt : "Sejuani créé une tempête de glace qui explose après 2 secondes (100/175/250 dégats) et étourdissant les ennemis 2/4/6 secondes",
        recommandedItemsArray : [complexObjects.coeur_gele, complexObjects.griffe, complexObjects.phantom_dancer]

      },
      shen: {
        name: "Shen",
        img: championImages.icons.shen,
        img_render: championImages.render.shen,
        propIconsArray : [originIcons.ninja,classIcons.blademaster],
        propArray : ["Ninja","Blademaster"],
        dmgArray : [65,117,234],
        hpArray : [650,1170,2340],
        as : 0.7,
        mr : 20,
        armure : 30,
        portee : 1,
        cout : 2,
        titreUlt: "Refuge de l'esprit",
        descriptionUlt : "Shen créé une zone autour de lui permettant aux alliés d'esquiver toutes les attaques pendant 3/4/5 secondes",
        recommandedItemsArray : [complexObjects.thornmail, complexObjects.griffe, complexObjects.shojin]

      },
      shyvana: {
        name: "Shyvana",
        img: championImages.icons.shyvana,
        img_render: championImages.render.shyvana,
        propIconsArray : [originIcons.dragon,classIcons.elementaliste],
        propArray : ["Dragon","Elémentaliste"],
        dmgArray : [50,90,180],
        hpArray : [650,1170,2340],
        as : 0.7,
        mr : 20,
        armure : 30,
        portee : 1,
        cout : 3,
        titreUlt: "Déscente du Dragon",
        descriptionUlt : "Shyvana s'envole et se transforme, elle gagne alors 100/150/200 dégats/coup et brule le sol pour 200/300/400 dégats pendant 3 secondes",
        recommandedItemsArray : [complexObjects.hydre_titanic, complexObjects.warmog, complexObjects.phantom_dancer]

      },
      swain: {
        name: "Swain",
        img: championImages.icons.swain,
        img_render: championImages.render.swain,
        propIconsArray : [originIcons.imperial,originIcons.demon,classIcons.blademaster],
        propArray : ["Imperial","Demon","Elémentaliste"],
        dmgArray : [65,117,234],
        hpArray : [850,1530,3060],
        as : 0.65,
        mr : 20,
        armure : 25,
        portee : 2,
        cout : 5,
        titreUlt: "Demonflare",
        descriptionUlt : "Swain se transforme pendant 6 secondes, infligeant 50/100/150 dégats et se soignant de 50/90/130pv par tick. Il explose en redevenant normal infligeant 300/600/900 dégats",
        recommandedItemsArray : [complexObjects.pistolame, complexObjects.griffe, complexObjects.phantom_dancer]

      },
      tristana: {
        name: "Tristana",
        img: championImages.icons.tristana,
        img_render: championImages.render.tristana,
        propIconsArray : [originIcons.yordle,classIcons.pistolero],
        propArray : ["Yordle","Pistolero"],
        dmgArray : [50,90,180],
        hpArray : [500,900,1800],
        as : 0.65,
        mr : 20,
        armure : 20,
        portee : 4,
        cout : 1,
        titreUlt: "Charge explosive",
        descriptionUlt : "Tristana place une bombe qui explose après 4 attaques ou 4 secondes, infligeant 150/225/300. Chaque coup augmente la puissance de 50%",
        recommandedItemsArray : [complexObjects.buff_rouge, complexObjects.canon_ultrarapide, complexObjects.dervish]

      },
      twisted_fate: {
        name: "Twisted Fate",
        img: championImages.icons.twisted_fate,
        img_render: championImages.render.twisted_fate,
        propIconsArray : [originIcons.pirate,classIcons.sorcier],
        propArray : ["Pirate","Sorcier"],
        dmgArray : [40,72,144],
        hpArray : [450,810,1620],
        as : 0.75,
        mr : 20,
        armure : 20,
        portee : 3,
        cout : 2,
        titreUlt: "Choisis une carte",
        descriptionUlt : "Twisted fate choisi une carte. Bleu restaure son mana et celui de ses alliés (20/35/50 mana. Jaune étourdi 2/3/4 secondes. Rouge inflige 150/250/350 dégats de zone",
        recommandedItemsArray : [complexObjects.shojin, complexObjects.seraph, complexObjects.guinsoo]

      },
      varus: {
        name: "Varus",
        img: championImages.icons.varus,
        img_render: championImages.render.varus,
        propIconsArray : [originIcons.demon,classIcons.ranger],
        propArray : ["Demon","Ranger"],
        dmgArray : [50,90,180],
        hpArray : [500,900,1800],
        as : 0.7,
        mr : 20,
        armure : 25,
        portee : 4,
        cout : 2,
        titreUlt: "Flèche perçante",
        descriptionUlt : "Varus tire en ligne droite une flèche infligeant 300/550/800 dégats sur 8 cases",
        recommandedItemsArray : [complexObjects.guinsoo, complexObjects.shojin, complexObjects.rabadon]

      },
      vayne: {
        name: "Vayne",
        img: championImages.icons.vayne,
        img_render: championImages.render.vayne,
        propIconsArray : [originIcons.noble,classIcons.ranger],
        propArray : ["Noble","Ranger"],
        dmgArray : [41,81,162],
        hpArray : [550,990,1980],
        as : 0.75,
        mr : 20,
        armure : 25,
        portee : 3,
        cout : 1,
        titreUlt: "Carreaux d'argent",
        descriptionUlt : "Vayne inflige des dégats bonus basées sur les PV maximum de l'ennemi toutes les trois attaques (8/10/12%)",
        recommandedItemsArray : [complexObjects.pistolame, complexObjects.griffe, complexObjects.phantom_dancer]

      },
      veigar: {
        name: "Veigar",
        img: championImages.icons.veigar,
        img_render: championImages.render.veigar,
        propIconsArray : [originIcons.yordle,classIcons.sorcier],
        propArray : ["Yordle","Sorcier"],
        dmgArray : [45,81,162],
        hpArray : [500,870,1720],
        as : 0.55,
        mr : 20,
        armure : 20,
        portee : 3,
        cout : 3,
        titreUlt: "Déflagration primordiale",
        descriptionUlt : "Veigar explose un ennemi aléatoirement (300/450/700 dégats), si il est de niveau inférieur à Veigar, il meurt instantanément",
        recommandedItemsArray : [complexObjects.shojin, complexObjects.griffe, complexObjects.guinsoo]

      },
      volibear: {
        name: "Volibear",
        img: championImages.icons.volibear,
        img_render: championImages.render.volibear,
        propIconsArray : [originIcons.glacial,classIcons.bagarreur],
        propArray : ["Glacial","Bagarreur"],
        dmgArray : [75,135,270],
        hpArray : [700,1260,2520],
        as : 0.55,
        mr : 20,
        armure : 35,
        portee : 1,
        cout : 3,
        titreUlt: "Griffe de foudre",
        descriptionUlt : "Les attaques rebondissent 3/4/5 fois sur les ennemis (+80/90/100% de dégats) pendant 20 secondes",
        recommandedItemsArray : [complexObjects.canon_ultrarapide, complexObjects.dervish, complexObjects.phantom_dancer]

      },
      warwick: {
        name: "Warwick",
        img: championImages.icons.warwick,
        img_render: championImages.render.warwick,
        propIconsArray : [originIcons.sauvage,classIcons.bagarreur],
        propArray : ["Sauvage","Bagarreur"],
        dmgArray : [50,90,180],
        hpArray : [600,1080,2160],
        as : 0.60,
        mr : 20,
        armure : 30,
        portee : 1,
        cout : 1,
        titreUlt: "Contrainte infinie",
        descriptionUlt : "Warwick bondit sur la cible la plus faible, l'immobilisant 1.5 secondes et la frappant 3 fois pour 150/225/300 dégats",
        recommandedItemsArray : [complexObjects.coeur_gele, complexObjects.warmog, complexObjects.hydre_titanic]

      },
      yasuo: {
        name: "Yasuo",
        img: championImages.icons.yasuo,
        img_render: championImages.render.yasuo,
        propIconsArray : [originIcons.exile,classIcons.blademaster],
        propArray : ["Exile","Blademaster"],
        dmgArray : [65,117,234],
        hpArray : [750,1350,2700],
        as : 1,
        mr : 20,
        armure : 35,
        portee : 1,
        cout : 5,
        titreUlt: "Tempête d'acier",
        descriptionUlt : "Yasuo frappe en avant avec son sabre (150/350/550 dégats sur 2 cases). La troisième attaque lance une tornade (6 cases) frappant en ligne droite et repoussant les ennemis 1.5 secondes",
        recommandedItemsArray : [complexObjects.pistolame, complexObjects.griffe, complexObjects.phantom_dancer]

      },
      zed: {
        name: "Zed",
        img: championImages.icons.zed,
        img_render: championImages.render.zed,
        propIconsArray : [originIcons.ninja,classIcons.assassin],
        propArray : ["Ninja","Assassin"],
        dmgArray : [65,117,234],
        hpArray : [500,900,1800],
        as : 0.65,
        mr : 20,
        armure : 25,
        portee : 1,
        cout : 2,
        titreUlt: "Shuriken rasoir",
        descriptionUlt : "Zed tire un shuriken en ligne droite, infligeant 200/300/400 dégats sur 4 cases",
        recommandedItemsArray : [complexObjects.pistolame, complexObjects.griffe, complexObjects.phantom_dancer]
      },

    }
  }
  render() {
    console.log(this.state.champArray)
      return (
        <ScrollView>
          <View style={styles.container}>
            {
              Object.keys(this.state.champArray).map((key, index)=>{
                return(
                <View style={styles.itemContainer}>
                  <DetailChamp champInfo={this.state.champArray[key]}></DetailChamp>
                </View>
                )
              })
            }
          </View>
        </ScrollView>
      );
    }
  }

  